### ISSUE TITLE
Failed to execute 'postMessage' on 'DOMWindow'

### ISSUE THREAD

**Issue by jackkinsella** [freshdesk/freshchat-widget#2]
I noticed a Javascript console error when using the widget in localhost:

```
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://wchat.freshchat.com') does not match the recipient window's origin ('http://localhost:1234').

// backtrace (one entry only)
postMessage @ widget.js:86
```

Any ideas what might be causing this or how to squash it?

**Comment by sankar-ganesh** [comment]
@jackkinsella Are you testing the widget from the page hosted in your local web server? Can you ensure if you are using the appropriate host in widget config as per https://developers.freshchat.com

**Comment by jackkinsella** [comment]
Yep -  I am testing from a page hosted on my local server.

The config is as per the docs, except I separated the Javascript out away from the HTML

```javascript
import 'freshchat-widget'

function initializeFreshchatWidget() {
  window.fcWidget.init({
    token: 'xxx',
    host: 'https://wchat.freshchat.com'
  })
}

document.addEventListener('DOMContentLoaded', initializeFreshchatWidget)

```

**Comment by jackkinsella** [comment]
From what I've read elsewhere online, the "Failed to execute 'postMessage' on 'DOMWindow" error is Chrome specific and happens when an iframe hasn't loaded yet (i.e. it's race condition like)? Certain SoundCloud and YouTube widgets once had this issue.

**Comment by jackkinsella** [comment]
Another possibility could be HTTPS/HTTP issues. It can probably be safely assumed that most production websites are HTTPS whereas local/development versions are HTTP.

**Comment by sankar-ganesh** [comment]
@jackkinsella As long as we target the window with the correct host we are good. Is this a recurring issue? Were you able to see the loaded widget when the error happened? I can help debug on this.

**Comment by jackkinsella** [comment]
It's a recurring issue, but it does not affect the ability of the widget to display or function.

**Comment by jackkinsella** [comment]
I was able to make it go away by wrapping the `initializeFreshchatWidget` in a `setTimeout` with just 100ms. 

i.e. this gives no errors
```javascript
document.addEventListener(
  'DOMContentLoaded', () => setTimeout(initializeFreshchatWidget, 100)
)
```

**Comment by sankar-ganesh** [comment]
ok great. I will check if I could synchronise the postMessage after frame window is load complete

**Comment by idubinets** [comment]
I have the same issue. is there another workaround?

**Comment by sankar-ganesh** [comment]
@idubinets Can you try async init?

```
(function(d, id){
	var fcJS;
	if (d.getElementById(id)) {return;}
	fcJS = d.createElement(s); fcJS.id = id;
	fcJS.src = <freshchat-web-widget-js>; // Refer path settings/web messenger settings in agent portal
	d.head.appendChild(fcJS);
}(document, 'freshchat-js-sdk'));
```

**Comment by nerf-qh** [comment]
This code seems working
```javascript
(function(d, id){
  var fcJS;
  if (d.getElementById(id)) {
    initFreshChat();
    return;
   }
  fcJS = d.createElement('script'); 
  fcJS.id = id;
  fcJS.async = true;
  fcJS.src = 'https://wchat.freshchat.com/js/widget.js';
  fcJS.onload = initFreshChat;
  d.head.appendChild(fcJS);
}(document, 'freshchat-js-sdk'));
```
