### ISSUE TITLE
Hosts needed for content security policy

### ISSUE THREAD

**Issue by jackkinsella** [freshdesk/freshchat-widget#3]
What CSP configuration does one need to run the freshchat widget with maximum security?

So far, I've seen _worker_ requests to `xxxxxxxxxx.webpush.freshchat.com` and `wchat.freshchat.com`.

What's the full policy needed? Do you have a doc similar to [the one published by Intercom](https://docs.intercom.com/configure-intercom-for-your-product-or-site/staying-secure/using-intercom-with-content-security-policy)?

**Comment by sankar-ganesh** [comment]
@jackkinsella  *.freshchat.com is enough

**Comment by jackkinsella** [comment]
Thanks. Any idea for which directives ([full list here in the Mozilla docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy))? E.g. worker-src, frame-src, script-src, etc.

**Comment by sankar-ganesh** [comment]
@jackkinsella Here you go:

frame-src script-src for "wchat.freshchat.com"
navigate-to for "*.freshchat.com"

PS: Please close the ticket if the issue is resolved. Thanks in advance

**Comment by jackkinsella** [comment]
Seems fine now. I probably won't be able to try it out in production for another week, so I'll close this issue now on the assumption that everything will be dandy.

Thx for the assistance.
