### ISSUE TITLE
Angular Support

### ISSUE THREAD

**Issue by MNPJason** [freshdesk/freshchat-widget#4]
Currently this does not Support Angular and would love for it to.

**Comment by sankar-ganesh** [comment]
This has been marked as deprecated. Please download the latest script as given in developers doc https://developers.freshchat.com

**Comment by MNPJason** [comment]
Your developer docs does not support angular and a plugin would be appreciated by the community

**Comment by sankar-ganesh** [comment]
Sure @MNPJason Will use this space to share one

**Comment by Suhas404** [comment]
we are waiting for the angular and react support.
