### ISSUE TITLE
Safari CSP Issue

### ISSUE THREAD

**Issue by dstew** [freshdesk/freshchat-widget#5]
It looks like you are using special code for Safari only when inserting the widget iframe. Instead of just setting the iframe's src to a url as you do with other browsers, you are writing content directly to the iframe's body. The content written is a script tag that then sets the iframe src to the url. This causes problems with my Content Security Policy because the content directly inserted into the iframe seems to inherit the parent page's CSP which doesn't allow inline scripts without a nonce. It works fine in other browsers because my CSP allows frame-src from your domain. Here's the code in question from widget.js:

```
load: function(t, n, i) {
    if (o.default.isSafariBrowser()) {
        var a = document.createElement("script")
        a.textContent = 'window.location = "'.concat(t, '"'), e = i.contentWindow, i.contentDocument.body.appendChild(a)
    } else
        e = window.open(t, n)
}
```

My first question is why do you have different code for Safari in the first place? I'm assuming there is/was some Safari bug related to iframe embedding, but I'm unaware of that.

Second, if this special code is (still) needed, can I pass in the nonce (e.g. in fcSettings) for you to apply to this script tag? I believe that would work.

**Comment by sankar-ganesh** [comment]
Safari switches the focus to the tab of the page which has inline iframe when it completes loading. The feature check that you highlighted in the above snippet helps to deal with that issue.

Thanks @dstew for letting us know! Yes passing nonce in the widget init payload will help. Will plan the fix for this and revert back soon.

**Comment by dstew** [comment]
FYI I'm currently just rewriting your exact script tag with the nonce (in Safari only) with this code:

```
var fci = document.getElementById('fc_widget');
var doc = fci && fci.contentDocument;
if (doc) {
	var oldScript = doc.body.firstChild;
	if (!oldScript.nonce && oldScript.textContent) {
		var newScript = document.createElement('script');
		newScript.type = 'text/javascript';
		newScript.nonce = '{nonce}';
		newScript.textContent = oldScript.textContent;
		doc.body.appendChild(newScript);
	}
}
```

That hack does work which proves the script will run once written with a nonce by your library.

That said, you could just read the nonce from the widget.js script tag as well (as opposed to a new input option in fcSettings). I believe anyone using a CSP that required nonces on inline scripts would have to put one on that anyway (maybe not with strict-dynamic but I don't think Safari supports that yet anyway).

**Comment by mohamed-imthihas-freshworks** [comment]
@dstew This is fixed. We have added `cspNonce` in widget payload, which user can pass to avoid browser focus shift issue. I am closing this issue now. Please reach out to us, if you have any queries.
